// <auto-generated />
using System;
using HouseHoldMoney.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HouseHoldMoney.Model.Migrations
{
    [DbContext(typeof(HouseHoldContext))]
    partial class HouseHoldContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("HouseHoldMoney.Model.HouseHoldMoney", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Amount");

                    b.Property<bool>("Automatically");

                    b.Property<string>("Description");

                    b.Property<string>("Organisation");

                    b.Property<Guid?>("PaymentID");

                    b.HasKey("ID");

                    b.HasIndex("PaymentID");

                    b.ToTable("HouseHoldMoneys");
                });

            modelBuilder.Entity("HouseHoldMoney.Model.Payment", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Apr");

                    b.Property<bool>("Aug");

                    b.Property<bool>("Dec");

                    b.Property<bool>("Feb");

                    b.Property<bool>("Jan");

                    b.Property<bool>("Jul");

                    b.Property<bool>("Jun");

                    b.Property<bool>("Mar");

                    b.Property<bool>("May");

                    b.Property<bool>("Nov");

                    b.Property<bool>("Oct");

                    b.Property<bool>("Sep");

                    b.Property<int>("TermOfPayment");

                    b.HasKey("ID");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            ID = new Guid("80578511-aa33-419b-8452-c6f31eb80042"),
                            Apr = true,
                            Aug = true,
                            Dec = true,
                            Feb = true,
                            Jan = true,
                            Jul = true,
                            Jun = true,
                            Mar = true,
                            May = true,
                            Nov = true,
                            Oct = true,
                            Sep = true,
                            TermOfPayment = 0
                        },
                        new
                        {
                            ID = new Guid("da3d9a67-77e0-4723-a918-44da5cff4686"),
                            Apr = false,
                            Aug = false,
                            Dec = false,
                            Feb = false,
                            Jan = true,
                            Jul = true,
                            Jun = false,
                            Mar = true,
                            May = true,
                            Nov = true,
                            Oct = false,
                            Sep = true,
                            TermOfPayment = 1
                        },
                        new
                        {
                            ID = new Guid("c7df48e6-b5d5-4c4b-a960-69e9335ac227"),
                            Apr = true,
                            Aug = true,
                            Dec = true,
                            Feb = true,
                            Jan = false,
                            Jul = false,
                            Jun = true,
                            Mar = false,
                            May = false,
                            Nov = false,
                            Oct = true,
                            Sep = false,
                            TermOfPayment = 1
                        },
                        new
                        {
                            ID = new Guid("43644941-8078-43f5-81fb-0d71fb902a99"),
                            Apr = true,
                            Aug = false,
                            Dec = false,
                            Feb = false,
                            Jan = true,
                            Jul = true,
                            Jun = false,
                            Mar = false,
                            May = false,
                            Nov = false,
                            Oct = true,
                            Sep = false,
                            TermOfPayment = 2
                        },
                        new
                        {
                            ID = new Guid("bffb2d5a-cee1-41d6-a777-51ba40363f51"),
                            Apr = false,
                            Aug = true,
                            Dec = false,
                            Feb = true,
                            Jan = false,
                            Jul = false,
                            Jun = false,
                            Mar = false,
                            May = true,
                            Nov = true,
                            Oct = false,
                            Sep = false,
                            TermOfPayment = 2
                        },
                        new
                        {
                            ID = new Guid("e2b5b3f2-c5a1-4bf0-9a53-f61836d6702e"),
                            Apr = false,
                            Aug = false,
                            Dec = true,
                            Feb = false,
                            Jan = false,
                            Jul = false,
                            Jun = true,
                            Mar = true,
                            May = false,
                            Nov = false,
                            Oct = false,
                            Sep = true,
                            TermOfPayment = 2
                        },
                        new
                        {
                            ID = new Guid("c8a5c3e2-8b0f-41f6-9223-efa8be522869"),
                            Apr = false,
                            Aug = false,
                            Dec = false,
                            Feb = false,
                            Jan = true,
                            Jul = true,
                            Jun = false,
                            Mar = false,
                            May = false,
                            Nov = false,
                            Oct = false,
                            Sep = false,
                            TermOfPayment = 3
                        },
                        new
                        {
                            ID = new Guid("988dd526-d831-461e-865b-8e6aae2cc8d9"),
                            Apr = false,
                            Aug = true,
                            Dec = false,
                            Feb = true,
                            Jan = false,
                            Jul = false,
                            Jun = false,
                            Mar = false,
                            May = false,
                            Nov = false,
                            Oct = false,
                            Sep = false,
                            TermOfPayment = 3
                        },
                        new
                        {
                            ID = new Guid("d73e06e0-e76d-4450-b6d8-40b85350a912"),
                            Apr = false,
                            Aug = true,
                            Dec = false,
                            Feb = true,
                            Jan = false,
                            Jul = false,
                            Jun = false,
                            Mar = false,
                            May = false,
                            Nov = false,
                            Oct = false,
                            Sep = false,
                            TermOfPayment = 3
                        },
                        new
                        {
                            ID = new Guid("f0d8f3cf-c6bc-41e9-afa1-666e278cb599"),
                            Apr = true,
                            Aug = false,
                            Dec = false,
                            Feb = false,
                            Jan = false,
                            Jul = false,
                            Jun = false,
                            Mar = false,
                            May = false,
                            Nov = false,
                            Oct = true,
                            Sep = false,
                            TermOfPayment = 3
                        },
                        new
                        {
                            ID = new Guid("bb1b7cca-86ae-43d9-93a9-bc100449584f"),
                            Apr = false,
                            Aug = false,
                            Dec = false,
                            Feb = false,
                            Jan = false,
                            Jul = false,
                            Jun = false,
                            Mar = false,
                            May = true,
                            Nov = true,
                            Oct = false,
                            Sep = false,
                            TermOfPayment = 3
                        },
                        new
                        {
                            ID = new Guid("82ff28fa-d9ce-4b7d-a233-e8b0b2758739"),
                            Apr = false,
                            Aug = false,
                            Dec = true,
                            Feb = false,
                            Jan = false,
                            Jul = false,
                            Jun = true,
                            Mar = false,
                            May = false,
                            Nov = false,
                            Oct = false,
                            Sep = false,
                            TermOfPayment = 3
                        },
                        new
                        {
                            ID = new Guid("6c9780b0-9e27-4833-afbc-3225bf38c7a9"),
                            Apr = false,
                            Aug = false,
                            Dec = false,
                            Feb = false,
                            Jan = true,
                            Jul = true,
                            Jun = false,
                            Mar = false,
                            May = false,
                            Nov = false,
                            Oct = false,
                            Sep = false,
                            TermOfPayment = 4
                        },
                        new
                        {
                            ID = new Guid("ddfd6516-cc35-434b-84ad-85e69277f07a"),
                            Apr = false,
                            Aug = true,
                            Dec = false,
                            Feb = true,
                            Jan = false,
                            Jul = false,
                            Jun = false,
                            Mar = false,
                            May = false,
                            Nov = false,
                            Oct = false,
                            Sep = false,
                            TermOfPayment = 4
                        },
                        new
                        {
                            ID = new Guid("30b76e21-cfca-4882-87a6-ba167aa9d1b3"),
                            Apr = false,
                            Aug = false,
                            Dec = false,
                            Feb = false,
                            Jan = false,
                            Jul = false,
                            Jun = false,
                            Mar = true,
                            May = false,
                            Nov = false,
                            Oct = false,
                            Sep = true,
                            TermOfPayment = 4
                        },
                        new
                        {
                            ID = new Guid("12339fce-0adc-4610-a5b6-f41f2b910fa1"),
                            Apr = true,
                            Aug = false,
                            Dec = false,
                            Feb = false,
                            Jan = false,
                            Jul = false,
                            Jun = false,
                            Mar = false,
                            May = false,
                            Nov = false,
                            Oct = true,
                            Sep = false,
                            TermOfPayment = 4
                        },
                        new
                        {
                            ID = new Guid("6b8e1584-44d1-470a-90b1-1cd3d4c5c226"),
                            Apr = false,
                            Aug = false,
                            Dec = false,
                            Feb = false,
                            Jan = false,
                            Jul = false,
                            Jun = false,
                            Mar = false,
                            May = true,
                            Nov = true,
                            Oct = false,
                            Sep = false,
                            TermOfPayment = 4
                        },
                        new
                        {
                            ID = new Guid("bfef042c-aa45-4c4f-bd3d-a50a81e4e2be"),
                            Apr = false,
                            Aug = false,
                            Dec = true,
                            Feb = false,
                            Jan = false,
                            Jul = false,
                            Jun = true,
                            Mar = false,
                            May = false,
                            Nov = false,
                            Oct = false,
                            Sep = false,
                            TermOfPayment = 4
                        },
                        new
                        {
                            ID = new Guid("64b6d2a0-d95a-498a-afc3-59ec498b4410"),
                            Apr = false,
                            Aug = false,
                            Dec = false,
                            Feb = false,
                            Jan = true,
                            Jul = true,
                            Jun = false,
                            Mar = false,
                            May = false,
                            Nov = false,
                            Oct = false,
                            Sep = false,
                            TermOfPayment = 4
                        },
                        new
                        {
                            ID = new Guid("dcf397fe-c181-4286-92bd-1edd195b3895"),
                            Apr = false,
                            Aug = true,
                            Dec = false,
                            Feb = true,
                            Jan = false,
                            Jul = false,
                            Jun = false,
                            Mar = false,
                            May = false,
                            Nov = false,
                            Oct = false,
                            Sep = false,
                            TermOfPayment = 4
                        },
                        new
                        {
                            ID = new Guid("971ebfca-f605-4563-a1f5-04f3b367f078"),
                            Apr = false,
                            Aug = false,
                            Dec = false,
                            Feb = false,
                            Jan = false,
                            Jul = false,
                            Jun = false,
                            Mar = true,
                            May = false,
                            Nov = false,
                            Oct = false,
                            Sep = true,
                            TermOfPayment = 4
                        },
                        new
                        {
                            ID = new Guid("b6fb1f15-6640-4780-805f-daee9ca938b4"),
                            Apr = true,
                            Aug = false,
                            Dec = false,
                            Feb = false,
                            Jan = false,
                            Jul = false,
                            Jun = false,
                            Mar = false,
                            May = false,
                            Nov = false,
                            Oct = true,
                            Sep = false,
                            TermOfPayment = 4
                        },
                        new
                        {
                            ID = new Guid("38b01a81-9261-45a7-b268-c5a0d3efcb18"),
                            Apr = false,
                            Aug = false,
                            Dec = false,
                            Feb = false,
                            Jan = false,
                            Jul = false,
                            Jun = false,
                            Mar = false,
                            May = true,
                            Nov = true,
                            Oct = false,
                            Sep = false,
                            TermOfPayment = 4
                        },
                        new
                        {
                            ID = new Guid("35f69fd9-30dc-46a2-9ff1-7a6b087b10ea"),
                            Apr = false,
                            Aug = false,
                            Dec = true,
                            Feb = false,
                            Jan = false,
                            Jul = false,
                            Jun = true,
                            Mar = false,
                            May = false,
                            Nov = false,
                            Oct = false,
                            Sep = false,
                            TermOfPayment = 4
                        });
                });

            modelBuilder.Entity("HouseHoldMoney.Model.HouseHoldMoney", b =>
                {
                    b.HasOne("HouseHoldMoney.Model.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentID");
                });
#pragma warning restore 612, 618
        }
    }
}
